source 'https://rubygems.org'

gem 'dbmanager', :path => '../..'
gem 'rails', '3.2.5'
gem 'mysql2'
gem 'jquery-rails'

group :assets do
  gem 'sass-rails',   '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'
  gem 'uglifier', '>= 1.0.3'
end
